# 7.5 Exception Handling: Processing the Incorrect Response

An exception indicates a problem that occurs while a program executes. 

exception 表示 a problem 發生, 當 a program 執行

The name “exception” suggests that the problem occurs infrequently — if the “rule” is that a statement normally executes correctly, then the problem represents the “exception to the rule.” 

exception 表示 problem 很少 occurs, 假設 rule is statement 正常執行, 那麼 problem 代表 rule 的例外


Exception handling helps you create fault-tolerant programs that can resolve (or handle) exceptions.

exception handling 可以幫助你創造可以接收一些錯誤的 programs

In many cases, this allows a program to continue executing as if no problems were encountered. 

在很多例子上, exception 可以讓 program 持續執行假如沒有 problems

For example, the StudentPoll application still displays results (Fig. 7.8), even though
one of the responses was out of range. 

對於這一個例子來說, 這一個 program 還是顯示出 results, 雖然有一個 responses 是錯誤的

More severe problems might prevent a program from continuing normal execution, instead requiring the program to notify the user of the problem, then terminate. 

很大的 problems 可能會導致 program 無法執行

When the JVM or a method detects a problem, such as an invalid array index or an invalid method argument, it throws an exception—that is, an exception occurs.

當 JVM or a method 偵測到 a problem, 他就會丟出 exception

Methods in your own classes can also throw exceptions, as you’ll learn in Chapter 8.

## 7.5.1 The try Statement

To handle an exception, place any code that might throw an exception in a try statement
(lines 17–26). 

要 handle an exception, 要把 code 放在 try statement

```java
        try
            {
                ++frequency[responses[answer]];
            }
            catch (ArrayIndexOutOfBoundsException e)
            {
                System.out.println(e); // invokes toString method
                System.out.printf(" responses[%d] = %d%n%n", answer, responses[answer]);

```


The try block (lines 17–20) contains the code that might throw an exception, and the catch block (lines 21–26) contains the code that handles the exception if one
occurs. 

try 裡面放的是正常執行的, catch 裡面放的是當 exception 發生的時候要做的事

You can have many catch blocks to handle different types of exceptions that might
be thrown in the corresponding try block. 

可以有很多的 catch blocks 去 handle different types of exceptions

When line 19 correctly increments an element of the frequency array, lines 21–26 are ignored. 

如果 try statement 執行, catch 就不會執行

The braces that delimit the bodies of the try and catch blocks are required.

需要加 {} 才能讓 program 執行

## 7.5.2 Executing the catch Block

When the program encounters the invalid value 14 in the responses array, it attempts to
add 1 to ```frequency[14]```, which is outside the bounds of the array — the frequency array has only six elements (with indexes 0–5). 

當 program 遇到了不合法的值 14 的時候, 一開始會企圖加 1 到 ```frequency[14]``` 裡面, 但是這一個 frequency array 只有 0 - 5 而已

Because array bounds checking is performed at execution time, the JVM generates an exception—specifically line 19 throws an ```ArrayIndexOutOfBoundsException``` to notify the program of this problem. 

因為 array bounds checking 是從 execution time 定義的, JVM 會產生一個 exception


At this point the try block terminates and the catch block begins executing—if you declared any local
variables in the try block, they’re now out of scope (and no longer exist), so they’re not accessible in the catch block.

在這一個時候 try 會中止執行, catch block 開始執行, 如果 try block 裡面有 local variable, 那麼這時候 local variable 就會消失, catch block 也不會知道有這一個 loca variable


The catch block declares an exception parameter (e) of type (IndexOutOfRangeException). 

catch block 會宣告一個 exception parameter (e)

The catch block can handle exceptions of the specified type. 

Inside the catch block, you can use the parameter’s identifier to interact with a caught exception object.

在 catch block 裡面, 可以用 parameter's identifier 去跟 exception object 作互動


## 7.5.3 toString Method of the Exception Parameter

When lines 21–26 catch the exception, the program displays a message indicating the
problem that occurred. 

當 catch the exception, the program 會顯示 message 表示 problem 發生了

Line 23 implicitly calls the exception object’s toString method to get the error message that’s implicitly stored in the exception object and display it. 

call exception 的 object ```toString``` method 去接收到 error message, 那這一個 error message 會間接的存在 exception object 裡面並且顯示出來

Once the message is displayed in this example, the exception is considered handled and the program continues with the next statement after the catch block’s closing brace. 

一旦 message 被顯示出來, exception 就會被妥當地做處理, 然後 the program 會繼續執行

In this example, the end of the for statement is reached (line 27), so the program continues with the
increment of the control variable in line 15. 

We discuss exception handling again in Chapter 8, and more deeply in Chapter 11.